import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
const inter = Inter({ subsets: ["latin"] });
import React from "react";
import StoreProvider from "@/redux/StoreProvider";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="bg-white">
                {/* <React.StrictMode> */}
                <StoreProvider>
                    <Header />
                    <main className="overflow-x-hidden">
                        <AntdRegistry>{children}</AntdRegistry>
                    </main>
                    <Footer />
                </StoreProvider>

                {/* </React.StrictMode> */}
            </body>
        </html>
    );
}
