import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/app/StoreProvider";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
const inter = Inter({ subsets: ["latin"] });
import React from 'react';
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <React.StrictMode> */}
        <StoreProvider>
          <Header />
          <main>
            <AntdRegistry>{children}</AntdRegistry>
          </main>
          <Footer />
        </StoreProvider>

        {/* </React.StrictMode> */}


      </body>
    </html>
  );
}
